### ISSUE TITLE
Print Cooling Fan Pin Assignment. 

### ISSUE THREAD

**Issue by Talha909** [codiac2600/SKR-MK3s-V1.4-Beta#12]
I saw the config file. In that file  you assign the Print cooling fan on P2_04. Why you did not used the P2_03.

**Comment by codiac2600** [comment]
The SKR V1.4 only has 1 PWM accessible pin for fans which is P2.3 which is the FAN0 pin. We have two fans that need to be accessible which is the part cooling fan and the heatsink fan. 

Every other fan port is always on so if you want the heatsink fan to kick in only when the hotend is heating we have to use the HE1 pin which is P2.4. 

Hopefully in the future there will be more user controllable fan pins on newer SKR boards until then using other open ports is the best way to get a pwm scalable fan for print cooling and another fan controllable when the hotend reaches 50C.
