### ISSUE TITLE
MKS 1.4 Turbo / Homing X Y / MK2.5s

### ISSUE THREAD

**Issue by onkelfunny** [codiac2600/SKR-MK3s-V1.4-Beta#14]
Hello Chris,

I have installed the MK3s version for MKS 1.4 Turbo. Currently the Bear 2.5s parts are installed. But I will replace them with the MK3s parts.

Z Homing works like it should.  With Y and X the axis moves only briefly. I have not connected the end stops. 

Here a link to a video: https://filebin.net/631rxdbz8si9yxiz/IMG_0119.MOV

What could be the reason?

Thanks

**Comment by onkelfunny** [comment]
i have connected another motor without load. Unfortunately the same problem. It can't be the stepper driver, I replaced it several times.

Strangely enough, this problem only occurs when homing. The axes can be moved normally via the "Motion -> Move Axis" menu.

**Comment by codiac2600** [comment]
Your setup runs 12V right now. You’ll need to make a custom firmware for 12V and then also tweak the homing currents and sensorless homing sensitivity.

**Comment by onkelfunny** [comment]
I have compiled the firmware with your config files myself. I have already set CHOPPER_TIMING to CHOPPER_DEFAULT_12V. Do I have to change anything else for 12V?

I try to adjust the values for SENSORLESS_HOMING.

**Comment by codiac2600** [comment]
Under the TMC settings increase the homing current.

**Comment by onkelfunny** [comment]
I have tested these values

`
#define X_CURRENT       800
#define X_CURRENT_HOME  X_CURRENT
`

`
#define X_STALL_SENSITIVITY  10
...OR...
#define X_STALL_SENSITIVITY 200
`

Unfortunately still no success :(

**Comment by codiac2600** [comment]
X current should be about 400mA. Try 300 as the homing current. 800 is waaaay too high.

**Comment by onkelfunny** [comment]
no luck with this values :(

**Comment by onkelfunny** [comment]
I have commented on SENSORLESS_HOMING. Unfortunately still no success. Which is also noticeable, if I turn the X axis home the motor turns very briefly in the wrong direction. In the direction of the power supply.

**Comment by onkelfunny** [comment]
Hello Chris,
I found the problem. I cut the diagnostic pin from all the drivers. Didn't read your manual right.

Sorry for wasting your time. :(
