### ISSUE TITLE
Picture of Wired SKR Board

### ISSUE THREAD

**Issue by jsmithgmail** [codiac2600/SKR-MK3s-V1.4-Beta#17]
Can you please post a picture of a wired SKR board for the Bear?  I realize you have a wiring guide, but appears the motors, fans, etc have to be wired with a JST connector.  The hotend fan has 3 wires, but the SKR only accepts 2.  Just want to confirm we use the red/black wires for the fan.

**Comment by mstewart1987** [comment]
Yes it’s just the red/black wires for the fan.  

Mark Stewart
