### ISSUE TITLE
i cant get p.i.n.d.a to triggers skr 1.4 turbo

### ISSUE THREAD

**Issue by angelshce22** [codiac2600/SKR-MK3s-V1.4-Beta#5]
i have wiring like in the pdf and firmware uploaded but in proterface whit m119 cant get to trigger

**Comment by codiac2600** [comment]
Is the light on the pinda turning on and off when a piece of metal is placed nearby?

**Comment by angelshce22** [comment]
> 
> 
> Is the light on the pinda turning on and off when a piece of metal is placed nearby?

Yes

**Comment by codiac2600** [comment]
I should have asked first. Did you compile your own firmware or are you using one of the final BIN firmware from this GitHub?

**Comment by angelshce22** [comment]
> 
> 
> I should have asked first. Did you compile your own firmware or are you using one of the final BIN firmware from this GitHub?
own compile , to reverse steppers but dident changue any more

**Comment by angelshce22** [comment]
@codiac2600 okay , whit Final BIN  works
